"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.RESPONSES_KEY = exports.MESSAGE_TYPE = void 0;

/**
 * Message type
 */
var MESSAGE_TYPE = {
  ERROR: "danger",
  SUCCESS: "success"
};
/**
 * Responses key
 */

exports.MESSAGE_TYPE = MESSAGE_TYPE;
var RESPONSES_KEY = {
  E_BAD_REQUEST: "E_BAD_REQUEST",
  E_BAD_REQUEST_BODY: "E_BAD_REQUEST_BODY",
  E_CANNOT_ACCESS_SERVICE: "E_CANNOT_ACCESS_SERVICE",
  E_CREDENTIALS_INVALID: "E_CREDENTIALS_INVALID",
  E_DEFAULT: "E_DEFAULT",
  E_INTERNAL_SERVER_ERROR: "E_INTERNAL_SERVER_ERROR",
  E_INVALID_RESET_REQUEST: "E_INVALID_RESET_REQUEST",
  E_MISSING_PARAM: "E_MISSING_PARAM",
  E_PASSWORD_TOO_SHORT: "E_PASSWORD_TOO_SHORT",
  E_RESOURCE_ALREADY_PRESENT: "E_RESOURCE_ALREADY_PRESENT",
  E_RESOURCE_NOT_FOUND: "E_RESOURCE_NOT_FOUND",
  E_TOKEN_EXPIRED: "E_TOKEN_EXPIRED",
  E_USER_ALREADY_EXISTING: "E_USER_ALREADY_EXISTING",
  E_USER_DISABLED: "E_USER_DISABLED",
  E_USER_NOT_CONFIRMED: "E_USER_NOT_CONFIRMED",
  E_USER_NOT_FOUND: "E_USER_NOT_FOUND",
  E_WRONG_CONFIRMATION_ID: "E_WRONG_CONFIRMATION_ID",
  OK_DEFAULT: "OK_DEFAULT",
  OK_EXIT: "OK_EXIT",
  OK_RESET: "OK_RESET",
  OK_RESET_REQUEST: "OK_RESET_REQUEST",
  OK_USER_CONFIRMED: "OK_USER_CONFIRMED",
  OK_USER_CREATED: "OK_USER_CREATED"
};
exports.RESPONSES_KEY = RESPONSES_KEY;